"""empty message

Revision ID: 68ccdad3e9fa
Revises: 47d70c4634de
Create Date: 2023-04-30 15:55:51.269804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ccdad3e9fa'
down_revision = '47d70c4634de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_chat_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_group_id'], ['chat_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_group_id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_group_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'chat_group', ['chat_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chat_group_id')

    op.drop_table('user_chat_group')
    op.drop_table('chat_group')
    # ### end Alembic commands ###
